from __future__ import annotations

import re

_CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff]")

# These are the curated names already reviewed for the first TradingView catalog.
CURATED_NAMES_ZH: dict[str, str] = {
    "US.TV.ADP.EMPLOYMENT": "ADP就业变化",
    "US.TV.BALANCE.TRADE": "美国贸易差额",
    "US.TV.CHALLENGER.CUTS": "挑战者裁员",
    "US.TV.CLAIMS.4W": "初请失业金四周均值",
    "US.TV.CONTINUING.CLAIMS": "续请失业救济人数",
    "US.TV.GOV.DEBT.GDP": "美国政府债务占GDP",
    "US.TV.GOVERNMENT.PAYROLLS": "政府就业变化",
    "US.TV.HOURLY.EARNINGS.MOM": "平均时薪环比",
    "US.TV.HOURLY.EARNINGS.YOY": "平均时薪同比",
    "US.TV.INFLATION.YOY": "美国通胀率同比",
    "US.TV.INITIAL.CLAIMS": "初次申请失业救济",
    "US.TV.INTEREST.RATE": "美国利率",
    "US.TV.JOB.OFFERS": "职位空缺与工作邀请",
    "US.TV.JOB.QUITS": "主动离职人数",
    "US.TV.LABOR.PARTICIPATION": "劳动参与率",
    "US.TV.MANUFACTURING.PAYROLLS": "制造业就业变化",
    "US.TV.NONFARM": "非农就业变化",
    "US.TV.NONFARM.PRIVATE": "私人非农就业变化",
    "US.TV.POPULATION": "美国人口",
    "US.TV.PRODUCTIVITY": "美国生产率",
    "US.TV.TAXES": "美国税收",
    "US.TV.UNEMPLOYMENT.RATE": "美国失业率",
    "US.TV.WEEKLY.HOURS": "平均每周工时",
}

_PHRASES: tuple[tuple[str, str], ...] = (
    (r"\bCore Pce Prices\b", "核心PCE价格"),
    (r"\bCpi Trimmed Mean\b", "截尾均值CPI"),
    (r"\bCore Producer Prices\b", "核心生产者价格"),
    (r"\bIpc Fipe\b", "IPC-Fipe"),
    (r"\bNational Wealth Fund Liquid Assets\b", "主权财富基金流动资产"),
    (r"\bChanges In Inventories\b", "库存变化"),
    (r"\bKansas Fed Composite Index\b", "堪萨斯联储综合指数"),
    (r"\bPhilly Fed Capex Index\b", "费城联储资本支出指数"),
    (r"\bHouses Permits\b", "住宅许可"),
    (r"\bRics House Price Balance\b", "RICS房价差额"),
    (r"\bApi Crude Oil Stock Change\b", "API原油库存变化"),
    (r"\bRedbook Index\b", "红皮书指数"),
    (r"\bGross Fixed Capital Formation\b", "固定资本形成总额"),
    (r"\bGross National Product\b", "国民生产总值"),
    (r"\bClaimant Count Change\b", "失业救济申请人数变化"),
    (r"\bDebt Balance Auto Loans\b", "汽车贷款余额"),
    (r"\bDebt Balance Credit Cards\b", "信用卡贷款余额"),
    (r"\bDebt Balance Mortgages\b", "抵押贷款余额"),
    (r"\bDebt Balance Student Loans\b", "学生贷款余额"),
    (r"\bEmployment Cost Index Benefits\b", "就业成本指数：福利"),
    (r"\bEmployment Cost Index Wages\b", "就业成本指数：工资"),
    (r"\bFull Time Employment\b", "全职就业"),
    (r"\bPart Time Employment\b", "非全职就业"),
    (r"\bHiring Plans Announcements\b", "招聘计划公告"),
    (r"\bHarmonised Unemployment Rate\b", "调和失业率"),
    (r"\bJob Vacancy Rate\b", "职位空缺率"),
    (r"\bNonfarm Productivity\b", "非农生产率"),
    (r"\bOvertime Pay\b", "加班薪酬"),
    (r"\bCore Consumer Prices\b", "核心消费价格"),
    (r"\bCore Inflation Rate\b", "核心通胀率"),
    (r"\bCorelogic Dwelling Prices\b", "CoreLogic住宅价格"),
    (r"\bCpi With Fixed Interest Rate\b", "固定利率CPI"),
    (r"\bTrimmed Mean Cpi\b", "截尾均值CPI"),
    (r"\bCpi Seasonally Adjusted\b", "季节调整CPI"),
    (r"\bGdp Chain Price Index\b", "GDP链式价格指数"),
    (r"\bGdp Deflator\b", "GDP平减指数"),
    (r"\bMid Month Core Inflation Rate\b", "月中核心通胀率"),
    (r"\bMonthly Cpi Indicator\b", "月度CPI指标"),
    (r"\bProducer Price Index Input\b", "生产者价格指数投入项"),
    (r"\bProducer Price Inflation\b", "生产者价格通胀"),
    (r"\bTokyo Core Cpi\b", "东京核心CPI"),
    (r"\bCentral Bank Balance Sheet\b", "央行资产负债表"),
    (r"\bEuro Short Term Rate\b", "欧元短期利率"),
    (r"\bFed Capital Account Surplus\b", "美联储资本账户盈余"),
    (r"\bLonger Term Refinancing Operations\b", "长期再融资操作"),
    (r"\bProxy Funds Rate\b", "代理基金利率"),
    (r"\bSecured Overnight Financing Rate\b", "担保隔夜融资利率"),
    (r"\bSterling Overnight Index Average Rate\b", "英镑隔夜指数平均利率"),
    (r"\bFreight Traffic Civil Aviation\b", "民航货运量"),
    (r"\bFreight Traffic Highways\b", "公路货运量"),
    (r"\bFreight Traffic Railway\b", "铁路货运量"),
    (r"\bFreight Traffic Waterways\b", "水路货运量"),
    (r"\bGlobal Dairy Trade Price Index\b", "全球乳制品贸易价格指数"),
    (r"\bNet Long Term Tic Flows\b", "TIC长期净流动"),
    (r"\bPublic Sector Net Debt\b", "公共部门净债务"),
    (r"\bBusiness Survey Index Large Manufacturing Firms\b", "大型制造企业商业调查指数"),
    (r"\bChicago Fed National Activity Index\b", "芝加哥联储全国活动指数"),
    (r"\bDallas Fed Manufacturing Employment Index\b", "达拉斯联储制造业就业指数"),
    (r"\bDallas Fed Manufacturing New Orders Index\b", "达拉斯联储制造业新订单指数"),
    (r"\bDallas Fed Manufacturing Prices Paid Index\b", "达拉斯联储制造业支付价格指数"),
    (r"\bDallas Fed Manufacturing Shipments Index\b", "达拉斯联储制造业出货指数"),
    (r"\bDallas Fed Services Revenues Index\b", "达拉斯联储服务业收入指数"),
    (r"\bEase Of Doing Business Ranking\b", "营商便利度排名"),
    (r"\bEconomy Watchers Survey Outlook\b", "经济观察家调查展望"),
    (r"\bEconomy Watchers Survey\b", "经济观察家调查"),
    (r"\bIfo Assessment Of The Business Situation\b", "IFO企业状况评估"),
    (r"\bKansas Fed Prices Paid Index\b", "堪萨斯联储支付价格指数"),
    (r"\bKansas Fed Employment Index\b", "堪萨斯联储就业指数"),
    (r"\bKansas Fed Manufacturing Index\b", "堪萨斯联储制造业指数"),
    (r"\bKansas Fed Shipments Index\b", "堪萨斯联储出货指数"),
    (r"\bLogistics Managers Index Future\b", "物流经理指数：未来"),
    (r"\bNew York Current Business Conditions Index\b", "纽约当前商业状况指数"),
    (r"\bNy Empire State Employment Index\b", "纽约联储帝国州就业指数"),
    (r"\bNy Empire State Manufacturing Index\b", "纽约联储帝国州制造业指数"),
    (r"\bNy Empire State New Orders Index\b", "纽约联储帝国州新订单指数"),
    (r"\bNy Empire State Prices Paid Index\b", "纽约联储帝国州支付价格指数"),
    (r"\bNy Empire State Shipments Index\b", "纽约联储帝国州出货指数"),
    (r"\bPhiladelphia Fed Manufacturing Index\b", "费城联储制造业指数"),
    (r"\bRichmond Fed Manufacturing Shipments Index\b", "里士满联储制造业出货指数"),
    (r"\bTankan Large Manufacturing Outlook\b", "短观大型制造业展望"),
    (r"\bTankan Non Manufacturing Outlook\b", "短观非制造业展望"),
    (r"\bAnz Roy Morgan Consumer Confidence Index\b", "澳新银行-罗伊·摩根消费者信心指数"),
    (r"\bConsumer Confidence Price Trends\b", "消费者信心价格趋势"),
    (r"\bRetail Sales Control Group\b", "零售销售控制组"),
    (r"\bRetail Sales Ex Gas And Autos\b", "剔除汽油和汽车的零售销售"),
    (r"\bUsed Car Prices\b", "二手车价格"),
    (r"\bExisting Home Sales\b", "成屋销售"),
    (r"\bNahb Housing Market Index\b", "NAHB住房市场指数"),
    (r"\bInvestment Lending For Homes\b", "住房投资贷款"),
    (r"\bMortgage Approvals\b", "抵押贷款批准量"),
    (r"\bMortgage Originations\b", "抵押贷款发放量"),
    (r"\bNational Home Price Index\b", "全国房价指数"),
    (r"\bNationwide House Price Index\b", "Nationwide房价指数"),
    (r"\bPrivate House Approvals\b", "私人住宅批准量"),
    (r"\bMba Purchase Index\b", "MBA购房指数"),
    (r"\bResidential Property Prices\b", "住宅房地产价格"),
    (r"\bNatural Gas Stocks Capacity\b", "天然气库存容量"),
    (r"\bNatural Gas Stocks Inventory\b", "天然气库存量"),
    (r"\bNatural Gas Stocks Withdrawal\b", "天然气库存提取量"),
    (r"\bCo2 Emissions\b", "二氧化碳排放量"),
    (r"\bNorth Rhine Westphalia\b", "北莱茵-威斯特法伦"),
    (r"\bBaden Wuerttemberg\b", "巴登-符腾堡"),
    (r"\bBrandenburg\b", "勃兰登堡"),
    (r"\bBavaria\b", "巴伐利亚"),
    (r"\bHesse\b", "黑森"),
    (r"\bSaxony\b", "萨克森"),
    (r"\bTokyo\b", "东京"),
    (r"\bMichigan 5 Year Inflation Expectations\b", "密歇根大学5年通胀预期"),
    (r"\bMichigan Inflation Expectations\b", "密歇根大学通胀预期"),
    (r"\bCore Pce Price Index\b", "核心PCE价格指数"),
    (r"\bPce Price Index\b", "PCE价格指数"),
    (r"\bConsumer Price Index\b", "消费者价格指数"),
    (r"\bProducer Price Index\b", "生产者价格指数"),
    (r"\bCore Producer Price Index\b", "核心生产者价格指数"),
    (r"\bCase Shiller Home Price Index\b", "标普CoreLogic凯斯-席勒房价指数"),
    (r"\bFull Year\b", "全年"),
    (r"\bPer Capita\b", "人均"),
    (r"\bDebt To Income\b", "债务收入比"),
    (r"\bDebt To Gdp\b", "债务占GDP"),
    (r"\bTo Gdp\b", "占GDP"),
    (r"\bExcluding Food Energy And Trade Services\b", "不含食品、能源和贸易服务"),
    (r"\bExcluding Food And Energy\b", "不含食品和能源"),
    (r"\bExcluding Transportation\b", "不含运输"),
    (r"\bExcluding Defense\b", "不含国防"),
    (r"\bExcluding Autos\b", "不含汽车"),
    (r"\bExcluding Fuel\b", "不含燃料"),
    (r"\bIncluding Bonuses\b", "含奖金"),
    (r"\bIncluding Bonus\b", "含奖金"),
    (r"\bExcluding Bonuses\b", "不含奖金"),
    (r"\bExcluding Bonus\b", "不含奖金"),
    (r"\bFrom Agriculture\b", "农业"),
    (r"\bFrom Construction\b", "建筑业"),
    (r"\bFrom Manufacturing\b", "制造业"),
    (r"\bFrom Mining\b", "采矿业"),
    (r"\bFrom Public Administration\b", "公共管理"),
    (r"\bFrom Services\b", "服务业"),
    (r"\bFrom Transport\b", "运输业"),
    (r"\bFrom Utilities\b", "公用事业"),
    (r"\bExternal Demand Contribution\b", "外部需求贡献"),
    (r"\bAggregate Demand\b", "总需求"),
    (r"\bNon Oil Sector\b", "非石油部门"),
    (r"\bOil Sector\b", "石油部门"),
    (r"\bNon Eu Countries\b", "非欧盟国家"),
    (r"\bNew Passenger Car Registrations\b", "新乘用车注册量"),
    (r"\bStrategic Petroleum Reserve Crude Oil Stocks\b", "战略石油储备原油库存"),
    (r"\bCrude Oil Stocks Change\b", "原油库存变化"),
    (r"\bCrude Oil Imports From Russia\b", "俄罗斯原油进口量"),
    (r"\bNatural Gas Imports From Russia\b", "俄罗斯天然气进口量"),
    (r"\bAverage Hourly Earnings\b", "平均时薪"),
    (r"\bAverage Weekly Earnings\b", "平均周薪"),
    (r"\bAverage House Prices\b", "平均房价"),
    (r"\bAverage Mortgage Size\b", "平均抵押贷款规模"),
    (r"\bBuilding Capital Expenditure\b", "建筑资本支出"),
    (r"\bHousing Starts Single Family\b", "单户住宅开工"),
    (r"\bHousing Starts Multi Family\b", "多户住宅开工"),
    (r"\bNew Residential Sales\b", "新建住宅销售"),
    (r"\bPending Home Sales Index\b", "成屋签约销售指数"),
    (r"\bMortgage Applications\b", "抵押贷款申请"),
    (r"\bMortgage Refinance Index\b", "抵押贷款再融资指数"),
    (r"\bMortgage Market Index\b", "抵押贷款市场指数"),
    (r"\bHousehold Spending\b", "家庭支出"),
    (r"\bConsumer Spending\b", "居民消费支出"),
    (r"\bPersonal Spending\b", "个人支出"),
    (r"\bPersonal Savings\b", "个人储蓄"),
    (r"\bDisposable Personal Income\b", "个人可支配收入"),
    (r"\bPersonal Income\b", "个人收入"),
    (r"\bConsumer Confidence\b", "消费者信心"),
    (r"\bEconomic Optimism Index\b", "经济乐观指数"),
    (r"\bBusiness Confidence Index\b", "企业信心指数"),
    (r"\bBusiness Climate Indicator\b", "企业景气指标"),
    (r"\bBusiness Conditions Index\b", "商业状况指数"),
    (r"\bEconomic Activity Index\b", "经济活动指数"),
    (r"\bWeekly Economic Index\b", "周度经济指数"),
    (r"\bLeading Economic Index\b", "领先经济指数"),
    (r"\bCoincident Index\b", "同步指数"),
    (r"\bComposite Leading Indicator\b", "综合领先指标"),
    (r"\bJob Advertisements\b", "招聘广告数量"),
    (r"\bJob Vacancies\b", "职位空缺数"),
    (r"\bJobs To Applications Ratio\b", "职位申请比"),
    (r"\bJob Layoffs And Discharges\b", "裁员与解雇人数"),
    (r"\bJob Quits Rate\b", "主动离职率"),
    (r"\bLong Term Unemployment Rate\b", "长期失业率"),
    (r"\bYouth Unemployment Rate\b", "青年失业率"),
    (r"\bLiving Wage Family\b", "家庭生活工资"),
    (r"\bLiving Wage Individual\b", "个人生活工资"),
    (r"\bRetirement Age Men\b", "男性退休年龄"),
    (r"\bRetirement Age Women\b", "女性退休年龄"),
    (r"\bPandemic Unemployment Assistance Claims\b", "疫情失业援助申请"),
    (r"\bEmployment Cost Index\b", "就业成本指数"),
    (r"\bUnit Labour Costs\b", "单位劳动成本"),
    (r"\bUnit Labor Costs\b", "单位劳动成本"),
    (r"\bReal Earnings\b", "实际收入"),
    (r"\bNegotiated Wage Growth\b", "协商工资增长"),
    (r"\bWages High Skilled\b", "高技能劳动者工资"),
    (r"\bWages Low Skilled\b", "低技能劳动者工资"),
    (r"\bWages In Manufacturing\b", "制造业工资"),
    (r"\bMoney Supply\b", "货币供应量"),
    (r"\bForeign Exchange Reserves\b", "外汇储备"),
    (r"\bForeign Bond Investment\b", "外国债券投资"),
    (r"\bForeign Stock Investment\b", "外国股票投资"),
    (r"\bInvestment In Foreign Securities\b", "对外证券投资"),
    (r"\bForeign Direct Investment\b", "外国直接投资"),
    (r"\bCurrent Account\b", "经常账户"),
    (r"\bCapital Flows\b", "资本流动"),
    (r"\bTerms Of Trade\b", "贸易条件"),
    (r"\bGoods Trade Balance\b", "货物贸易差额"),
    (r"\bGoods Trade Deficit\b", "货物贸易逆差"),
    (r"\bCurrent Account Goods\b", "经常账户货物"),
    (r"\bCurrent Account Services\b", "经常账户服务"),
    (r"\bDirect Investment Liabilities\b", "直接投资负债"),
    (r"\bRemittances\b", "汇款"),
    (r"\bTourist Arrivals\b", "游客到达量"),
    (r"\bTourism Revenues\b", "旅游收入"),
    (r"\bExternal Debt\b", "外债"),
    (r"\bGovernment Debt\b", "政府债务"),
    (r"\bGovernment Revenues\b", "政府收入"),
    (r"\bGovernment Spending\b", "政府支出"),
    (r"\bFiscal Expenditure\b", "财政支出"),
    (r"\bBudget To Gdp\b", "预算占GDP"),
    (r"\bGovernment Budget Value\b", "政府预算金额"),
    (r"\bInterest Payments On Government Debt\b", "政府债务利息支出"),
    (r"\bMilitary Expenditure\b", "军事支出"),
    (r"\bNational Wealth Fund Assets\b", "主权财富基金资产"),
    (r"\bPublic Sector Net Borrowing\b", "公共部门净借款"),
    (r"\bPublic Sector Net Debt\b", "公共部门净债务"),
    (r"\bTax Revenue\b", "税收收入"),
    (r"\bTreasury Cash Balance\b", "财政部现金余额"),
    (r"\bCorporate Tax Rate\b", "企业所得税率"),
    (r"\bPersonal Income Tax Rate\b", "个人所得税率"),
    (r"\bSocial Security Rate For Companies\b", "企业社会保障缴费率"),
    (r"\bSocial Security Rate For Employees\b", "雇员社会保障缴费率"),
    (r"\bSocial Security Rate\b", "社会保障缴费率"),
    (r"\bSales Tax Rate\b", "销售税率"),
    (r"\bWithholding Tax Rate\b", "预扣税率"),
    (r"\bBank Balance Sheet\b", "银行资产负债表"),
    (r"\bCentral Bank Balance Sheet\b", "央行资产负债表"),
    (r"\bBanks Balance Sheet\b", "银行资产负债表"),
    (r"\bCredit Card Accounts\b", "信用卡账户数"),
    (r"\bCredit Card Spending\b", "信用卡消费"),
    (r"\bConsumer Credit\b", "消费信贷"),
    (r"\bBank Lending Rate\b", "银行贷款利率"),
    (r"\bLoan Prime Rate\b", "贷款市场报价利率"),
    (r"\bLoans To Private Sector\b", "私人部门贷款"),
    (r"\bLoans To Banks\b", "银行贷款"),
    (r"\bDebt Balance\b", "债务余额"),
    (r"\bCash Reserve Ratio\b", "现金准备金率"),
    (r"\bDeposit Interest Rate\b", "存款利率"),
    (r"\bEffective Federal Funds Rate\b", "有效联邦基金利率"),
    (r"\bFederal Funds Rate\b", "联邦基金利率"),
    (r"\bInterbank Rate\b", "银行间利率"),
    (r"\bOvernight Interbank Average Rate\b", "隔夜银行间平均利率"),
    (r"\bRepo Rate\b", "回购利率"),
    (r"\bReverse Repo Rate\b", "逆回购利率"),
    (r"\bRefinancing Operations\b", "再融资操作"),
    (r"\bPurchases Of Government Bonds\b", "政府债券购买"),
    (r"\bLiquidity Injections Via Reverse Repo\b", "通过逆回购投放流动性"),
    (r"\bLiquidity Injections Via Mlf\b", "通过MLF投放流动性"),
    (r"\bCentral Bank Lending Rate\b", "央行贷款利率"),
    (r"\bInterest Rate On New Mortgages\b", "新发放抵押贷款利率"),
    (r"\bInflation Expectations\b", "通胀预期"),
    (r"\bInflation Rate\b", "通胀率"),
    (r"\bCore Inflation Rate\b", "核心通胀率"),
    (r"\bInflation Gauge\b", "通胀指标"),
    (r"\bRent Inflation\b", "租金通胀"),
    (r"\bEnergy Inflation\b", "能源通胀"),
    (r"\bFood Inflation\b", "食品通胀"),
    (r"\bGoods Inflation\b", "商品通胀"),
    (r"\bServices Inflation\b", "服务通胀"),
    (r"\bCommodity Prices\b", "大宗商品价格"),
    (r"\bEnergy Prices\b", "能源价格"),
    (r"\bFood Price Index\b", "食品价格指数"),
    (r"\bDairy Price Index\b", "乳制品价格指数"),
    (r"\bCereals Price Index\b", "谷物价格指数"),
    (r"\bMeat Price Index\b", "肉类价格指数"),
    (r"\bSugar Price Index\b", "糖价格指数"),
    (r"\bOils Price Index\b", "油脂价格指数"),
    (r"\bWholesale Prices\b", "批发价格"),
    (r"\bImport Prices\b", "进口价格"),
    (r"\bExport Prices\b", "出口价格"),
    (r"\bProducer Prices\b", "生产者价格"),
    (r"\bCpi Housing Utilities\b", "CPI住房与公用事业"),
    (r"\bCpi Transportation\b", "CPI交通"),
    (r"\bTrimmed Mean Cpi\b", "截尾均值CPI"),
    (r"\bWeighted Median Cpi\b", "加权中位数CPI"),
    (r"\bMedian Cpi\b", "中位数CPI"),
    (r"\bHarmonised Index Of Consumer Prices\b", "调和消费者价格指数"),
    (r"\bHarmonised Inflation Rate\b", "调和通胀率"),
    (r"\bSelling Price Expectations\b", "销售价格预期"),
    (r"\bRetail Price Index\b", "零售价格指数"),
    (r"\bWholesale Price Index\b", "批发价格指数"),
    (r"\bIndustrial Production\b", "工业生产"),
    (r"\bManufacturing Production\b", "制造业生产"),
    (r"\bMining Production\b", "采矿业生产"),
    (r"\bCapacity Utilization\b", "产能利用率"),
    (r"\bFactory Orders\b", "工厂订单"),
    (r"\bDurable Goods Orders\b", "耐用品订单"),
    (r"\bNew Orders\b", "新订单"),
    (r"\bBusiness Inventories\b", "企业库存"),
    (r"\bWholesale Inventories\b", "批发库存"),
    (r"\bWholesale Sales\b", "批发销售"),
    (r"\bRetail Inventories\b", "零售库存"),
    (r"\bRetail Sales\b", "零售销售"),
    (r"\bConstruction Spending\b", "建筑支出"),
    (r"\bPrivate Investment\b", "私人投资"),
    (r"\bFixed Asset Investment\b", "固定资产投资"),
    (r"\bCapital Expenditure\b", "资本支出"),
    (r"\bCar Production\b", "汽车产量"),
    (r"\bCar Registrations\b", "汽车注册量"),
    (r"\bElectricity Production\b", "发电量"),
    (r"\bElectricity Price\b", "电价"),
    (r"\bGold Production\b", "黄金产量"),
    (r"\bGold Reserves\b", "黄金储备"),
    (r"\bNatural Gas Imports\b", "天然气进口量"),
    (r"\bNatural Gas Stocks\b", "天然气库存"),
    (r"\bGasoline Production\b", "汽油产量"),
    (r"\bGasoline Prices\b", "汽油价格"),
    (r"\bGasoline Stocks\b", "汽油库存"),
    (r"\bHeating Oil Stocks\b", "取暖油库存"),
    (r"\bDistillate Stocks\b", "馏分油库存"),
    (r"\bCrude Oil Production\b", "原油产量"),
    (r"\bCrude Oil Rigs\b", "原油钻机数"),
    (r"\bCrude Oil Stocks\b", "原油库存"),
    (r"\bCrude Oil Imports\b", "原油进口量"),
    (r"\bRefinery Crude Runs\b", "炼厂原油加工量"),
    (r"\bPlant Machinery Capital Expenditure\b", "厂房与机械资本支出"),
    (r"\bSupply Chain Pressure Index\b", "供应链压力指数"),
    (r"\bSmall Business Sentiment Index\b", "小企业信心指数"),
    (r"\bConsumer Confidence Price Trends\b", "消费者价格趋势预期"),
    (r"\bHouse Price Index\b", "房价指数"),
    (r"\bHouse Prices\b", "房价"),
    (r"\bHome Price Index\b", "房价指数"),
    (r"\bHome Sales\b", "房屋销售"),
    (r"\bHome Loans\b", "住房贷款"),
    (r"\bHome Ownership Rate\b", "住房拥有率"),
    (r"\bHousing Market Index\b", "住房市场指数"),
    (r"\bHousing Credit\b", "住房信贷"),
    (r"\bHousing Starts\b", "住宅开工"),
    (r"\bBuilding Permits\b", "建筑许可"),
    (r"\bApartment Permits\b", "公寓许可"),
    (r"\bMortgage Rate\b", "抵押贷款利率"),
    (r"\bProperty Investment\b", "房地产投资"),
    (r"\bProperty Prices\b", "房地产价格"),
    (r"\bRental Prices\b", "租赁价格"),
    (r"\bPrice To Rent Ratio\b", "房价租金比"),
    (r"\bHospital Beds\b", "医院床位"),
    (r"\bIcu Beds\b", "重症监护床位"),
    (r"\bMedical Doctors\b", "医生人数"),
    (r"\bAsylum Applications\b", "庇护申请"),
    (r"\bPrecipitation\b", "降水量"),
    (r"\bTemperature\b", "气温"),
)

_WORDS: dict[str, str] = {
    "inactivity": "闲置",
    "unemployed": "失业",
    "core": "核心",
    "trimmed": "截尾",
    "mean": "均值",
    "budget": "预算",
    "credit": "信贷",
    "optimism": "乐观",
    "cement": "水泥",
    "dallas": "达拉斯联储",
    "fed": "联储",
    "distillate": "馏分油",
    "grain": "谷物",
    "changes": "变化",
    "composite": "综合",
    "lmi": "LMI",
    "transportation": "运输",
    "warehouse": "仓储",
    "machine": "机床",
    "tool": "工具",
    "capex": "资本支出",
    "richmond": "里士满联储",
    "rigs": "钻机",
    "store": "门店",
    "cbi": "CBI",
    "trades": "贸易",
    "rics": "RICS",
    "adjusted": "调整",
    "activity": "活动",
    "advertisements": "广告",
    "agriculture": "农业",
    "annual": "年度",
    "applications": "申请",
    "announcements": "公告",
    "api": "API",
    "assessment": "评估",
    "assets": "资产",
    "average": "平均",
    "backlog": "积压订单",
    "balance": "余额",
    "bank": "银行",
    "bankruptcies": "破产数",
    "bonds": "债券",
    "business": "企业",
    "capital": "资本",
    "car": "汽车",
    "cash": "现金",
    "change": "变化",
    "claims": "申请",
    "climate": "景气",
    "conditions": "状况",
    "confidence": "信心",
    "construction": "建筑业",
    "consumption": "消费",
    "consumer": "居民消费",
    "corporate": "企业",
    "corruption": "腐败",
    "costs": "成本",
    "count": "人数",
    "crude": "原油",
    "current": "当前",
    "demand": "需求",
    "deposit": "存款",
    "developments": "发展",
    "direct": "直接",
    "discharges": "解雇",
    "distributive": "分销",
    "domestic": "国内",
    "durable": "耐用品",
    "economic": "经济",
    "economy": "经济",
    "electric": "电动",
    "employment": "就业",
    "energy": "能源",
    "excluding": "不含",
    "expenditure": "支出",
    "expectations": "预期",
    "exports": "出口",
    "external": "外部",
    "family": "家庭",
    "federal": "联邦",
    "financial": "金融",
    "fiscal": "财政",
    "food": "食品",
    "foreign": "外国",
    "freight": "货运",
    "fuel": "燃料",
    "fund": "基金",
    "funds": "基金",
    "gdp": "GDP",
    "global": "全球",
    "gold": "黄金",
    "goods": "商品",
    "government": "政府",
    "growth": "增长",
    "gross": "总额",
    "health": "健康",
    "heating": "取暖",
    "high": "高",
    "highways": "公路",
    "home": "住房",
    "house": "房屋",
    "households": "家庭",
    "housing": "住房",
    "hospitals": "医院",
    "hours": "工时",
    "imports": "进口",
    "including": "含",
    "index": "指数",
    "industrial": "工业",
    "industry": "行业",
    "inflation": "通胀",
    "injection": "投放",
    "inventories": "库存",
    "investment": "投资",
    "interest": "利率",
    "international": "国际",
    "leading": "领先",
    "liabilities": "负债",
    "liquid": "流动",
    "liquidity": "流动性",
    "loans": "贷款",
    "loan": "贷款",
    "low": "低",
    "manufacturing": "制造业",
    "market": "市场",
    "machinery": "机械",
    "meat": "肉类",
    "median": "中位数",
    "military": "军事",
    "minimum": "最低",
    "monthly": "月度",
    "mortgage": "抵押贷款",
    "natural": "天然",
    "nurses": "护士",
    "new": "新",
    "non": "非",
    "oil": "石油",
    "operations": "操作",
    "orders": "订单",
    "overnight": "隔夜",
    "output": "产出",
    "passenger": "乘用车",
    "payments": "支付",
    "personal": "个人",
    "population": "人口",
    "potential": "潜在",
    "prices": "价格",
    "price": "价格",
    "private": "私人",
    "production": "生产",
    "productivity": "生产率",
    "profits": "利润",
    "public": "公共",
    "quarterly": "季度",
    "rate": "率",
    "real": "实际",
    "revenues": "收入",
    "retail": "零售",
    "retirement": "退休",
    "reverse": "逆",
    "risk": "风险",
    "sales": "销售",
    "saving": "储蓄",
    "savings": "储蓄",
    "secured": "有担保",
    "services": "服务",
    "shipments": "出货",
    "short": "短期",
    "single": "单户",
    "skilled": "技能",
    "small": "小型",
    "spending": "支出",
    "stocks": "库存",
    "stock": "库存",
    "student": "学生",
    "sugar": "糖",
    "supplier": "供应商",
    "supply": "供给",
    "survey": "调查",
    "tax": "税",
    "taxes": "税收",
    "temperature": "气温",
    "term": "期限",
    "tertiary": "第三产业",
    "time": "时间",
    "total": "总计",
    "trade": "贸易",
    "transport": "运输",
    "tourism": "旅游",
    "unemployment": "失业",
    "utilities": "公用事业",
    "vacancies": "空缺",
    "vehicle": "车辆",
    "volatility": "波动",
    "wage": "工资",
    "wages": "工资",
    "waterways": "水运",
    "weekly": "周度",
    "wholesale": "批发",
    "women": "女性",
    "youth": "青年",
    "yoy": "同比",
    "mom": "环比",
    "qoq": "季度环比",
    "annualized": "年化",
    "aircraft": "飞机",
    "anz": "澳新银行",
    "account": "账户",
    "approvals": "批准量",
    "auto": "汽车",
    "benefits": "福利",
    "capacity": "容量",
    "cards": "卡",
    "central": "央行",
    "chain": "链式",
    "civil": "民用",
    "cfnai": "CFNAI",
    "cpi": "CPI",
    "cushing": "库欣",
    "copper": "铜",
    "corn": "玉米",
    "dairy": "乳制品",
    "defense": "国防",
    "deflator": "平减指数",
    "deliveries": "交付",
    "doing": "营商",
    "dwelling": "住宅",
    "ease": "便利度",
    "earnings": "收入",
    "employed": "就业",
    "euro": "欧元",
    "existing": "成屋",
    "empire": "帝国州",
    "formation": "形成",
    "firms": "企业",
    "fixed": "固定",
    "flows": "流动",
    "full": "全职",
    "future": "未来",
    "group": "组",
    "harmonised": "调和",
    "hiring": "招聘",
    "houses": "住宅",
    "ifo": "IFO",
    "individuals": "个人",
    "input": "投入",
    "inventory": "库存",
    "ism": "ISM",
    "kansas": "堪萨斯联储",
    "large": "大型",
    "labour": "劳动力",
    "lending": "贷款",
    "logistics": "物流",
    "long": "长期",
    "longer": "长期",
    "managers": "经理",
    "mba": "MBA",
    "michigan": "密歇根大学",
    "monitor": "监测",
    "morgan": "摩根",
    "motorbike": "摩托车",
    "nahb": "NAHB",
    "national": "全国",
    "nationwide": "Nationwide",
    "nfib": "NFIB",
    "nonfarm": "非农",
    "ny": "纽约",
    "outlook": "展望",
    "paid": "支付",
    "part": "部分",
    "persons": "人数",
    "philly": "费城联储",
    "philadelphia": "费城联储",
    "plant": "厂房",
    "product": "产品",
    "producer": "生产者",
    "property": "房地产",
    "proxy": "代理",
    "rank": "排名",
    "ranking": "排名",
    "railway": "铁路",
    "redbook": "Redbook",
    "reuters": "路透",
    "roy": "罗伊",
    "runs": "加工量",
    "seasonally": "季节性",
    "sector": "部门",
    "sentiment": "景气信心",
    "soy": "大豆",
    "state": "州",
    "steel": "钢铁",
    "sterling": "英镑",
    "stores": "商店",
    "situation": "状况",
    "tankan": "短观",
    "terrorism": "恐怖主义",
    "tic": "TIC",
    "traffic": "交通",
    "trends": "趋势",
    "used": "二手",
    "watchers": "观察家",
    "weapons": "武器",
    "wheat": "小麦",
    "withdrawal": "提取",
    "zew": "ZEW",
    "year": "年",
    "month": "月",
    "day": "日",
    "week": "周",
    "with": "含",
    "without": "不含",
    "to": "至",
    "of": "",
    "and": "与",
}


def _replace_phrases(value: str) -> str:
    for pattern, replacement in _PHRASES:
        value = re.sub(pattern, replacement, value, flags=re.IGNORECASE)
    return value


def _translate_words(value: str) -> str:
    pieces = re.findall(r"[A-Za-z]+|\d+(?:\.\d+)?|[^A-Za-z0-9]+", value)
    translated: list[str] = []
    for piece in pieces:
        if not piece or not piece[0].isalpha() or not piece.isascii():
            translated.append(piece)
            continue
        translated.append(_WORDS.get(piece.lower(), piece))
    return "".join(translated)


def _clean_spacing(value: str) -> str:
    value = re.sub(r"\s+", " ", value).strip()
    value = re.sub(
        r"(?<=[\u3400-\u4dbf\u4e00-\u9fff])\s+(?=[\u3400-\u4dbf\u4e00-\u9fff])",
        "",
        value,
    )
    value = re.sub(r"\s+([，。、：；（））])", r"\1", value)
    value = re.sub(r"([（(])\s+", r"\1", value)
    return value


def tradingview_name_zh(
    canonical_code: str,
    name_en: str,
    existing_name_zh: str | None = None,
) -> str:
    """Return a deterministic Chinese display name while preserving ``name_en``."""

    if existing_name_zh and existing_name_zh != name_en and _CJK_RE.search(existing_name_zh):
        return existing_name_zh
    curated = CURATED_NAMES_ZH.get(canonical_code)
    if curated:
        return curated

    translated = _clean_spacing(_translate_words(_replace_phrases(name_en)))
    if not _CJK_RE.search(translated):
        translated = f"{translated}指标".strip()
    return translated
