from __future__ import annotations

import csv
import hashlib
import io
import json
from calendar import monthrange
from dataclasses import dataclass
from datetime import UTC, date, datetime, time, timedelta
from decimal import Decimal
from functools import cached_property, lru_cache
from pathlib import Path
from statistics import median
from typing import Any
from uuid import UUID, uuid5

from .errors import AppError
from .schemas import (
    AICapabilityResponse,
    BrowserFacets,
    BrowserFacetValue,
    BrowserMetric,
    BrowserObservation,
    BrowserPagination,
    CapabilityStatus,
    ContributionResult,
    LicenseInfo,
    LineageInfo,
    ObservationMeta,
    ObservationPoint,
    ObservationResponse,
    ProviderInfo,
    RevisionItem,
    RevisionResponse,
    SeriesAnalyticsResponse,
    SeriesBrowserItem,
    SeriesBrowserResponse,
    SeriesCapabilities,
    SeriesDetail,
    SeriesStatistics,
    SeriesSummary,
    TaxonomyChildNode,
    TaxonomyChildrenResponse,
)
from .services.transforms import PERIODS_PER_YEAR, Point, transform_points

DEMO_AS_OF = datetime(2026, 8, 1, tzinfo=UTC)
DEMO_NAMESPACE = UUID("d14fd59d-843c-5eb4-b39f-e571950ebcf0")
DEMO_PROVIDER = ProviderInfo(
    code="DEMO_SYNTHETIC",
    name="MacroLens deterministic demo",
    attribution="Synthetic demonstration data generated by MacroLens.",
    license_class="SYNTHETIC",
)
DEMO_LICENSE = LicenseInfo(
    display_allowed=True,
    download_allowed=True,
    api_redistribution_allowed=True,
    ai_context_allowed=False,
    attribution_required=True,
    attribution_text=DEMO_PROVIDER.attribution,
)


def _demo_uuid(kind: str, value: str) -> UUID:
    return uuid5(DEMO_NAMESPACE, f"{kind}:{value}")


@dataclass(frozen=True, slots=True)
class DemoTaxonomyNode:
    code: str
    parent_code: str | None
    name_zh: str
    name_en: str | None
    node_type: str
    sort_order: int
    series_codes: tuple[str, ...]
    icon_key: str | None = None

    @property
    def id(self) -> UUID:
        return _demo_uuid("taxonomy", self.code)


@dataclass(frozen=True, slots=True)
class DemoSeries:
    canonical_code: str
    name_zh: str
    name_en: str | None
    frequency: str
    unit_code: str
    unit_label_zh: str
    seasonal_adjustment: str
    theme: str
    source_name: str
    dataset: str
    source_locator: dict[str, Any]
    description: str | None

    @property
    def id(self) -> UUID:
        return _demo_uuid("series", self.canonical_code)


@dataclass(frozen=True)
class DemoRegistry:
    tree_code: str
    nodes: tuple[DemoTaxonomyNode, ...]
    series: tuple[DemoSeries, ...]

    @cached_property
    def nodes_by_code(self) -> dict[str, DemoTaxonomyNode]:
        return {node.code: node for node in self.nodes}

    @cached_property
    def nodes_by_id(self) -> dict[UUID, DemoTaxonomyNode]:
        return {node.id: node for node in self.nodes}

    @cached_property
    def series_by_code(self) -> dict[str, DemoSeries]:
        return {item.canonical_code: item for item in self.series}

    @cached_property
    def series_by_id(self) -> dict[UUID, DemoSeries]:
        return {item.id: item for item in self.series}

    @cached_property
    def children_by_code(self) -> dict[str | None, tuple[DemoTaxonomyNode, ...]]:
        grouped: dict[str | None, list[DemoTaxonomyNode]] = {}
        for node in self.nodes:
            grouped.setdefault(node.parent_code, []).append(node)
        return {
            key: tuple(sorted(value, key=lambda item: (item.sort_order, item.code)))
            for key, value in grouped.items()
        }

    @cached_property
    def owner_by_series_code(self) -> dict[str, DemoTaxonomyNode]:
        return {series_code: node for node in self.nodes for series_code in node.series_codes}

    @property
    def max_depth(self) -> int:
        return max(len(self._path_for_node(node)) - 1 for node in self.nodes)

    def _path_for_node(self, node: DemoTaxonomyNode) -> tuple[str, ...]:
        path = [node.code]
        current = node
        while current.parent_code is not None:
            current = self.nodes_by_code[current.parent_code]
            path.append(current.code)
        return tuple(reversed(path))

    def path_for(self, canonical_code: str) -> tuple[str, ...]:
        try:
            return self._path_for_node(self.owner_by_series_code[canonical_code])
        except KeyError as exc:
            raise KeyError(f"Unknown demo series {canonical_code}") from exc

    def node_and_descendants(self, code: str) -> tuple[DemoTaxonomyNode, ...]:
        if code not in self.nodes_by_code:
            raise KeyError(code)
        result: list[DemoTaxonomyNode] = []
        pending = [self.nodes_by_code[code]]
        while pending:
            node = pending.pop()
            result.append(node)
            pending.extend(reversed(self.children_by_code.get(node.code, ())))
        return tuple(result)

    def leaf_series_codes(self, code: str) -> tuple[str, ...]:
        return tuple(
            series_code
            for node in self.node_and_descendants(code)
            for series_code in node.series_codes
        )


def _repo_root() -> Path:
    candidates = (Path("/app"), Path(__file__).resolve().parents[3])
    for candidate in candidates:
        if (candidate / "database" / "seed" / "source_registry.json").is_file():
            return candidate
    raise RuntimeError("Cannot locate MacroLens registries")


def _unit(item: dict[str, Any]) -> tuple[str, str]:
    label = str(item["unit"])
    mapping = {
        "%": "percent",
        "百分比": "percent",
        "百分点": "percentage_point",
        "指数": "index",
        "千人": "thousand_persons",
        "十亿美元": "billion_usd",
        "百万美元": "million_usd",
        "美元/小时": "usd_per_hour",
        "美元/桶": "usd_per_barrel",
        "标准差": "standard_deviation",
    }
    return mapping.get(label, str(item.get("kind") or label)), label


def _validate_registry(
    source_payload: dict[str, Any],
    taxonomy_payload: dict[str, Any],
) -> DemoRegistry:
    source_items = source_payload.get("indicators")
    node_items = taxonomy_payload.get("nodes")
    if not isinstance(source_items, list) or not isinstance(node_items, list):
        raise RuntimeError("Demo registries must contain indicators and nodes lists")
    expected = int(taxonomy_payload.get("expected_series_count", -1))
    source_codes = [str(item["canonical_code"]) for item in source_items]
    if len(source_codes) != expected or len(set(source_codes)) != expected or expected != 61:
        raise RuntimeError("Demo source registry must contain exactly 61 unique canonical codes")

    nodes = tuple(
        DemoTaxonomyNode(
            code=str(item["code"]),
            parent_code=str(item["parent_code"]) if item.get("parent_code") is not None else None,
            name_zh=str(item["name_zh"]),
            name_en=str(item["name_en"]) if item.get("name_en") else None,
            node_type=str(item["node_type"]),
            sort_order=int(item.get("sort_order", 0)),
            series_codes=tuple(str(code) for code in item.get("series_codes", [])),
            icon_key=str(item["icon_key"]) if item.get("icon_key") else None,
        )
        for item in node_items
    )
    by_code = {node.code: node for node in nodes}
    if len(by_code) != len(nodes):
        raise RuntimeError("Demo taxonomy node codes must be unique")
    roots = [node for node in nodes if node.parent_code is None]
    if len(roots) != 1 or roots[0].code != "root":
        raise RuntimeError("Demo taxonomy must have exactly one root node")
    for node in nodes:
        if node.parent_code is not None and node.parent_code not in by_code:
            raise RuntimeError(f"Unknown parent {node.parent_code} for node {node.code}")
        seen: set[str] = set()
        current = node
        depth = 0
        while current.parent_code is not None:
            if current.code in seen:
                raise RuntimeError(f"Cycle detected at demo taxonomy node {current.code}")
            seen.add(current.code)
            current = by_code[current.parent_code]
            depth += 1
            if depth > 64:
                raise RuntimeError("Demo taxonomy depth exceeds 64")

    owners: dict[str, str] = {}
    for node in nodes:
        for canonical_code in node.series_codes:
            if canonical_code in owners:
                previous_owner = owners[canonical_code]
                raise RuntimeError(
                    f"Demo series {canonical_code} belongs to both {previous_owner} and {node.code}"
                )
            owners[canonical_code] = node.code
    if set(owners) != set(source_codes):
        raise RuntimeError("Every demo series must belong to exactly one taxonomy node")

    top_level_name: dict[str, str] = {}
    for canonical_code, owner_code in owners.items():
        current = by_code[owner_code]
        while current.parent_code not in {None, "root"}:
            current = by_code[current.parent_code]
        top_level_name[canonical_code] = current.name_zh

    frequency_map = {"日度": "daily", "周度": "weekly", "月度": "monthly", "季度": "quarterly"}
    series: list[DemoSeries] = []
    for item in source_items:
        canonical_code = str(item["canonical_code"])
        unit_code, unit_label = _unit(item)
        series.append(
            DemoSeries(
                canonical_code=canonical_code,
                name_zh=str(item["name_zh"]),
                name_en=str(item["name_en"]) if item.get("name_en") else None,
                frequency=frequency_map[str(item["frequency"])],
                unit_code=unit_code,
                unit_label_zh=unit_label,
                seasonal_adjustment=str(item.get("seasonal_adjustment") or "not_specified"),
                theme=top_level_name[canonical_code],
                source_name=str(item["recommended_source"]),
                dataset=str(item.get("dataset") or "default"),
                source_locator=dict(item.get("locator") or {}),
                description="; ".join(str(value) for value in item.get("notes") or []) or None,
            )
        )
    registry = DemoRegistry(
        tree_code=str(taxonomy_payload["tree_code"]),
        nodes=nodes,
        series=tuple(series),
    )
    if registry.max_depth > 64:
        raise RuntimeError("Demo taxonomy depth exceeds 64")
    return registry


@lru_cache(maxsize=1)
def get_demo_registry() -> DemoRegistry:
    root = _repo_root()
    source_payload = json.loads(
        (root / "database" / "seed" / "source_registry.json").read_text(encoding="utf-8")
    )
    taxonomy_payload = json.loads(
        (root / "database" / "seed" / "taxonomy_registry.json").read_text(encoding="utf-8")
    )
    return _validate_registry(source_payload, taxonomy_payload)


def _series_or_404(series_id: UUID) -> DemoSeries:
    item = get_demo_registry().series_by_id.get(series_id)
    if item is None:
        raise AppError(404, "指标不存在", "没有找到该指标。", "series_not_found")
    return item


def _period_starts(frequency: str) -> list[date]:
    start = date(2014, 1, 1)
    end = DEMO_AS_OF.date()
    result: list[date] = []
    if frequency == "daily":
        current = start
        while current <= end:
            if current.weekday() < 5:
                result.append(current)
            current += timedelta(days=1)
    elif frequency == "weekly":
        current = start + timedelta(days=(4 - start.weekday()) % 7)
        while current <= end:
            result.append(current)
            current += timedelta(days=7)
    elif frequency == "monthly":
        year, month = start.year, start.month
        while date(year, month, 1) <= end:
            result.append(date(year, month, 1))
            month += 1
            if month == 13:
                year += 1
                month = 1
    else:
        year, month = start.year, 1
        while date(year, month, 1) <= end:
            result.append(date(year, month, 1))
            month += 3
            if month > 12:
                year += 1
                month = 1
    return result


def _period_end(period_start: date, frequency: str) -> date:
    if frequency == "weekly":
        return period_start + timedelta(days=6)
    if frequency == "monthly":
        return date(
            period_start.year,
            period_start.month,
            monthrange(period_start.year, period_start.month)[1],
        )
    if frequency == "quarterly":
        month = period_start.month + 2
        return date(period_start.year, month, monthrange(period_start.year, month)[1])
    return period_start


def _published_at(period_end: date, frequency: str) -> datetime:
    lag = {"daily": 1, "weekly": 5, "monthly": 25, "quarterly": 35}[frequency]
    return datetime.combine(period_end + timedelta(days=lag), time(13, 30), tzinfo=UTC)


def _value(series: DemoSeries, index: int) -> Decimal:
    digest = hashlib.sha256(series.canonical_code.encode("utf-8")).digest()
    seed = int.from_bytes(digest[:4], "big")
    if series.unit_code in {"percent", "percentage_point"}:
        base = Decimal(seed % 700) / Decimal(100)
        slope = Decimal((seed % 9) - 4) / Decimal(10_000)
    elif series.unit_code == "index":
        base = Decimal(85 + seed % 35)
        slope = Decimal((seed % 13) + 2) / Decimal(1_000)
    else:
        base = Decimal(50 + seed % 950)
        slope = Decimal((seed % 23) + 5) / Decimal(100)
    cycle = Decimal(((index + seed) % 17) - 8) / Decimal(20)
    return (base + slope * index + cycle).quantize(Decimal("0.01"))


@lru_cache(maxsize=128)
def demo_points(canonical_code: str) -> tuple[Point, ...]:
    series = get_demo_registry().series_by_code[canonical_code]
    points: list[Point] = []
    for index, period_start in enumerate(_period_starts(series.frequency)):
        period_end = _period_end(period_start, series.frequency)
        published_at = _published_at(period_end, series.frequency)
        if published_at > DEMO_AS_OF:
            continue
        points.append(
            Point(
                period_start=period_start,
                period_end=period_end,
                value=_value(series, index),
                value_text=None,
                status="ok",
                published_at=published_at,
                vintage_at=min(published_at + timedelta(days=7), DEMO_AS_OF),
            )
        )
    return tuple(points)


def _summary(series: DemoSeries) -> SeriesSummary:
    latest = demo_points(series.canonical_code)[-1]
    return SeriesSummary(
        id=series.id,
        canonical_code=series.canonical_code,
        name_zh=series.name_zh,
        name_en=series.name_en,
        theme=series.theme,
        frequency=series.frequency,
        unit_code=series.unit_code,
        unit_label_zh=series.unit_label_zh,
        default_transform="level",
        latest_period=latest.period_start,
        latest_value=latest.value,
        latest_vintage_at=latest.vintage_at if isinstance(latest.vintage_at, datetime) else None,
        provider=DEMO_PROVIDER,
    )


def demo_series_detail(series_id: UUID) -> SeriesDetail:
    series = _series_or_404(series_id)
    summary = _summary(series)
    points = demo_points(series.canonical_code)
    return SeriesDetail(
        **summary.model_dump(),
        description=series.description or "Deterministic synthetic demonstration series.",
        seasonal_adjustment=series.seasonal_adjustment,
        geography_code="US",
        decimal_places=2,
        status="active",
        first_period=points[0].period_start,
        aliases=[series.canonical_code, series.name_en]
        if series.name_en
        else [series.canonical_code],
        license=DEMO_LICENSE,
    )


def _serialize_taxonomy_node(node: DemoTaxonomyNode) -> dict[str, Any]:
    registry = get_demo_registry()
    return {
        "id": str(node.id),
        "code": node.code,
        "name_zh": node.name_zh,
        "name_en": node.name_en,
        "node_type": node.node_type,
        "icon_key": node.icon_key,
        "description": None,
        "series": [
            {
                "id": str(registry.series_by_code[code].id),
                "canonical_code": code,
                "name_zh": registry.series_by_code[code].name_zh,
                "name_en": registry.series_by_code[code].name_en,
                "frequency": registry.series_by_code[code].frequency,
                "unit": registry.series_by_code[code].unit_label_zh,
                "role": "primary",
            }
            for code in node.series_codes
        ],
        "children": [
            _serialize_taxonomy_node(child)
            for child in registry.children_by_code.get(node.code, ())
        ],
    }


def demo_taxonomy(tree_code: str, *, include_series: bool = True) -> dict[str, Any]:
    registry = get_demo_registry()
    if tree_code != registry.tree_code:
        raise AppError(404, "分类树不存在", "没有找到指定分类树。", "taxonomy_not_found")
    nodes = [_serialize_taxonomy_node(node) for node in registry.children_by_code[None]]
    if not include_series:
        pending = list(nodes)
        while pending:
            item = pending.pop()
            item["series"] = []
            pending.extend(item["children"])
    return {"tree_code": tree_code, "nodes": nodes, "data_mode": "demo"}


def demo_taxonomy_children(
    tree_code: str,
    *,
    parent_id: UUID | None,
    q: str | None,
    scope: str,
) -> TaxonomyChildrenResponse:
    registry = get_demo_registry()
    if tree_code != registry.tree_code:
        raise AppError(404, "分类树不存在", "没有找到指定分类树。", "taxonomy_not_found")
    parent = registry.nodes_by_id.get(parent_id) if parent_id is not None else None
    if parent_id is not None and parent is None:
        raise AppError(404, "分类节点不存在", "没有找到指定父节点。", "taxonomy_node_not_found")
    visible = (
        registry.nodes
        if scope == "all"
        else registry.children_by_code.get(parent.code if parent else None, ())
    )
    if q and q.strip():
        needle = q.strip().casefold()
        visible = tuple(
            node
            for node in visible
            if needle in node.code.casefold()
            or needle in node.name_zh.casefold()
            or needle in (node.name_en or "").casefold()
        )
    nodes = [
        TaxonomyChildNode(
            id=node.id,
            code=node.code,
            name_zh=node.name_zh,
            name_en=node.name_en,
            node_type=node.node_type,
            icon_key=node.icon_key,
            has_children=bool(registry.children_by_code.get(node.code)),
            direct_series_count=len(node.series_codes),
            descendant_series_count=len(registry.leaf_series_codes(node.code)),
        )
        for node in visible
    ]
    direct_series = (
        [_summary(registry.series_by_code[code]) for code in parent.series_codes]
        if parent is not None
        else []
    )
    return TaxonomyChildrenResponse(
        tree_code=tree_code,
        parent_id=parent_id,
        nodes=nodes,
        series=direct_series,
        data_mode="demo",
    )


def _metric(value: Decimal | None, unit: str, *, basis: str | None = None) -> BrowserMetric:
    return BrowserMetric(
        value=value,
        unit=unit,
        status="available" if value is not None else "unavailable",
        basis=basis,
        reason_code=None if value is not None else "insufficient_history",
        reason=None if value is not None else "Insufficient deterministic demo history.",
    )


def _browser_item(series: DemoSeries, taxonomy_order: int) -> SeriesBrowserItem:
    points = list(demo_points(series.canonical_code))
    current = points[-1]
    previous = points[-2]
    assert current.value is not None and previous.value is not None
    lag = PERIODS_PER_YEAR[series.frequency]
    yoy_value: Decimal | None = None
    if len(points) > lag and points[-1 - lag].value not in {None, Decimal(0)}:
        base = points[-1 - lag].value
        assert base is not None
        yoy_value = ((current.value / base) - 1) * 100
    change_unit = (
        "pp" if series.unit_code in {"percent", "percentage_point"} else series.unit_label_zh
    )
    period_change = ((current.value / previous.value) - 1) * 100 if previous.value else None

    def observation(point: Point) -> BrowserObservation:
        assert isinstance(point.vintage_at, datetime)
        return BrowserObservation(
            period_start=point.period_start,
            period_end=point.period_end,
            value=point.value,
            published_at=point.published_at if isinstance(point.published_at, datetime) else None,
            vintage_at=point.vintage_at,
        )

    return SeriesBrowserItem(
        series=_summary(series),
        current=observation(current),
        previous=observation(previous),
        change=_metric((current.value - previous.value).quantize(Decimal("0.01")), change_unit),
        period_change=_metric(
            period_change.quantize(Decimal("0.01")) if period_change is not None else None,
            "%",
            basis="period",
        ),
        yoy=_metric(
            yoy_value.quantize(Decimal("0.01")) if yoy_value is not None else None, "%", basis="yoy"
        ),
        license=DEMO_LICENSE,
        display_denied=False,
        source_status="ready",
        unavailable_reason_code=None,
        taxonomy_order=taxonomy_order,
        availability="available",
    )


def _facets(series: list[DemoSeries]) -> BrowserFacets:
    def values(attribute: str) -> list[BrowserFacetValue]:
        counts: dict[str, int] = {}
        for item in series:
            value = str(getattr(item, attribute))
            counts[value] = counts.get(value, 0) + 1
        return [
            BrowserFacetValue(value=value, label=value, count=count)
            for value, count in sorted(counts.items())
        ]

    return BrowserFacets(
        provider=[
            BrowserFacetValue(value=DEMO_PROVIDER.code, label=DEMO_PROVIDER.name, count=len(series))
        ],
        theme=values("theme"),
        frequency=values("frequency"),
        unit=values("unit_code"),
        seasonal_adjustment=values("seasonal_adjustment"),
    )


def demo_series_browser(
    *,
    q: str | None,
    node_id: UUID | None,
    provider: str | None,
    theme: str | None,
    frequency: str | None,
    unit: str | None,
    seasonal_adjustment: str | None,
    published_from: date | None,
    published_to: date | None,
    sort: str,
    order: str,
    limit: int,
    offset: int,
) -> SeriesBrowserResponse:
    registry = get_demo_registry()
    allowed_codes: set[str] | None = None
    if node_id is not None:
        node = registry.nodes_by_id.get(node_id)
        if node is None:
            raise AppError(
                404, "分类节点不存在", "没有找到指定分类节点。", "taxonomy_node_not_found"
            )
        allowed_codes = set(registry.leaf_series_codes(node.code))
    series = list(registry.series)
    if allowed_codes is not None:
        series = [item for item in series if item.canonical_code in allowed_codes]
    if q and q.strip():
        needle = q.strip().casefold()
        series = [
            item
            for item in series
            if needle in item.canonical_code.casefold()
            or needle in item.name_zh.casefold()
            or needle in (item.name_en or "").casefold()
        ]
    if provider and provider != DEMO_PROVIDER.code:
        series = []
    if theme:
        series = [item for item in series if item.theme == theme]
    if frequency:
        series = [item for item in series if item.frequency == frequency]
    if unit:
        series = [item for item in series if item.unit_code == unit]
    if seasonal_adjustment:
        series = [item for item in series if item.seasonal_adjustment == seasonal_adjustment]
    if published_from or published_to:

        def published_on(item: DemoSeries) -> date:
            published_at = demo_points(item.canonical_code)[-1].published_at
            assert isinstance(published_at, datetime)
            return published_at.date()

        series = [
            item
            for item in series
            if (published_from is None or published_on(item) >= published_from)
            and (published_to is None or published_on(item) <= published_to)
        ]
    order_by_code = {
        code: index
        for index, code in enumerate(code for node in registry.nodes for code in node.series_codes)
    }
    items = [_browser_item(item, order_by_code[item.canonical_code]) for item in series]
    sort_keys = {
        "taxonomy": lambda item: (item.taxonomy_order, item.series.canonical_code),
        "name": lambda item: (item.series.name_zh.casefold(), item.series.canonical_code),
        "current_period": lambda item: item.current.period_start if item.current else date.min,
        "current": lambda item: (
            item.current.value
            if item.current and item.current.value is not None
            else Decimal("-Infinity")
        ),
        "change": lambda item: (
            item.change.value if item.change.value is not None else Decimal("-Infinity")
        ),
        "period_change": lambda item: (
            item.period_change.value
            if item.period_change.value is not None
            else Decimal("-Infinity")
        ),
        "yoy": lambda item: item.yoy.value if item.yoy.value is not None else Decimal("-Infinity"),
    }
    items.sort(key=sort_keys[sort], reverse=order == "desc")
    total = len(items)
    return SeriesBrowserResponse(
        items=items[offset : offset + limit],
        facets=_facets(series),
        pagination=BrowserPagination(total=total, limit=limit, offset=offset),
        data_as_of=DEMO_AS_OF,
        data_mode="demo",
    )


def demo_observations(
    series_id: UUID,
    *,
    start: date | None,
    end: date | None,
    transform: str,
) -> ObservationResponse:
    series = _series_or_404(series_id)
    points = [
        point
        for point in demo_points(series.canonical_code)
        if (start is None or point.period_start >= start)
        and (end is None or point.period_start <= end)
    ]
    transformed = transform_points(points, transform, series.frequency)
    return ObservationResponse(
        series=_summary(series),
        data=[
            ObservationPoint(
                period_start=point.period_start,
                period_end=point.period_end,
                value=point.value,
                value_text=point.value_text,
                status=point.status,
                published_at=point.published_at
                if isinstance(point.published_at, datetime)
                else None,
                vintage_at=point.vintage_at
                if isinstance(point.vintage_at, datetime)
                else DEMO_AS_OF,
            )
            for point in transformed
        ],
        meta=ObservationMeta(
            data_as_of=DEMO_AS_OF,
            vintage=DEMO_AS_OF.isoformat(),
            transform=transform,
            frequency=series.frequency,
            unit=series.unit_label_zh if transform in {"level", "difference"} else "%",
            lineage=LineageInfo(
                provider=DEMO_PROVIDER.code,
                dataset="deterministic-demo",
                provider_series_id=series.canonical_code,
                source_series_id=int.from_bytes(
                    hashlib.sha256(series.canonical_code.encode()).digest()[:4], "big"
                ),
                source_locator={"mode": "demo", "source_registry": series.source_name},
            ),
            license=DEMO_LICENSE,
            data_mode="demo",
        ),
    )


def demo_revisions(series_id: UUID, *, start: date | None, end: date | None) -> RevisionResponse:
    series = _series_or_404(series_id)
    points = [
        point
        for point in demo_points(series.canonical_code)
        if (start is None or point.period_start >= start)
        and (end is None or point.period_start <= end)
    ][-24:]
    items: list[RevisionItem] = []
    for index, point in enumerate(points):
        assert point.value is not None and isinstance(point.vintage_at, datetime)
        delta = Decimal((index % 5) - 2) / Decimal(100)
        first_vintage = point.vintage_at - timedelta(days=7)
        items.append(
            RevisionItem(
                period_start=point.period_start,
                first_value=point.value - delta,
                latest_value=point.value,
                revision=delta,
                first_vintage_at=first_vintage,
                latest_vintage_at=point.vintage_at,
                versions=2,
            )
        )
    return RevisionResponse(series_id=series_id, items=items, data_as_of=DEMO_AS_OF)


def _statistics(points: list[Point]) -> SeriesStatistics:
    values = [point.value for point in points if point.value is not None]
    if not values:
        return SeriesStatistics(
            count=0,
            mean=None,
            median=None,
            min=None,
            max=None,
            stddev=None,
            current_percentile=None,
        )
    mean_value = sum(values, Decimal(0)) / len(values)
    variance = sum((value - mean_value) ** 2 for value in values) / len(values)
    percentile = Decimal(sum(value <= values[-1] for value in values)) * 100 / len(values)
    return SeriesStatistics(
        count=len(values),
        mean=mean_value.quantize(Decimal("0.01")),
        median=Decimal(median(values)).quantize(Decimal("0.01")),
        min=min(values),
        max=max(values),
        stddev=Decimal(str(float(variance) ** 0.5)).quantize(Decimal("0.01")),
        current_percentile=percentile.quantize(Decimal("0.01")),
    )


def demo_analytics(
    series_id: UUID,
    *,
    start: date | None,
    end: date | None,
    transform: str,
) -> SeriesAnalyticsResponse:
    series = _series_or_404(series_id)
    points = [
        point
        for point in demo_points(series.canonical_code)
        if (start is None or point.period_start >= start)
        and (end is None or point.period_start <= end)
    ]
    transformed = transform_points(points, transform, series.frequency)
    allowed = CapabilityStatus(allowed=True)
    capabilities = SeriesCapabilities(
        display=allowed,
        download=allowed,
        ai=CapabilityStatus(
            allowed=False, reason_code="demo_read_only", reason="Demo data mode is read-only."
        ),
        trend=allowed,
        history=allowed,
        revisions=allowed,
        documents=allowed,
        contributions=CapabilityStatus(
            allowed=False,
            reason_code="demo_contributions_unavailable",
            reason="Synthetic demo series do not have formula dependencies.",
        ),
    )
    return SeriesAnalyticsResponse(
        series=_summary(series),
        statistics=_statistics(transformed),
        next_release=None,
        contributions=ContributionResult(
            available=False,
            reason_code="demo_contributions_unavailable",
            reason="Synthetic demo series do not have formula dependencies.",
        ),
        capabilities=capabilities,
        data_as_of=DEMO_AS_OF,
        data_mode="demo",
    )


def demo_ai_capability(series_id: UUID) -> AICapabilityResponse:
    _series_or_404(series_id)
    return AICapabilityResponse(
        series_id=series_id,
        configured=False,
        allowed=False,
        reason_code="demo_read_only",
        reason="Demo data mode is read-only.",
    )


def _csv_safe(value: object) -> str:
    text = str(value).replace("\t", " ").replace("\r", " ").replace("\n", " ")
    return "'" + text if text.startswith(("=", "+", "-", "@")) else text


def demo_series_csv(
    series_id: UUID,
    *,
    start: date | None,
    end: date | None,
    transform: str,
) -> bytes:
    response = demo_observations(series_id, start=start, end=end, transform=transform)
    output = io.StringIO(newline="")
    writer = csv.writer(output)
    writer.writerow(
        [
            "series_id",
            "canonical_code",
            "name_zh",
            "period_start",
            "period_end",
            "value",
            "status",
            "published_at",
            "vintage_at",
            "data_as_of",
            "data_mode",
            "transform",
            "unit",
            "provider",
            "attribution",
        ]
    )
    for point in response.data:
        writer.writerow(
            [
                response.series.id,
                _csv_safe(response.series.canonical_code),
                _csv_safe(response.series.name_zh),
                point.period_start,
                point.period_end,
                point.value if point.value is not None else "",
                point.status,
                point.published_at.isoformat() if point.published_at else "",
                point.vintage_at.isoformat(),
                DEMO_AS_OF.isoformat(),
                "demo",
                transform,
                response.meta.unit,
                DEMO_PROVIDER.code,
                DEMO_PROVIDER.attribution or "",
            ]
        )
    return ("\ufeff" + output.getvalue()).encode("utf-8")


def demo_list_series(
    *,
    q: str | None,
    theme: str | None,
    provider: str | None,
    frequency: str | None,
    unit: str | None,
    limit: int,
    offset: int,
) -> dict[str, Any]:
    response = demo_series_browser(
        q=q,
        node_id=None,
        provider=provider,
        theme=theme,
        frequency=frequency,
        unit=unit,
        seasonal_adjustment=None,
        published_from=None,
        published_to=None,
        sort="taxonomy",
        order="asc",
        limit=limit,
        offset=offset,
    )
    return {
        "items": [item.series.model_dump(mode="json") for item in response.items],
        "total": response.pagination.total,
        "limit": limit,
        "offset": offset,
        "data_mode": "demo",
    }
